# Generated by Django 5.0.7 on 2024-07-19 07:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=255, unique=True)),
                ('coins', models.IntegerField(default=0)),
                ('limit', models.IntegerField(default=10)),
                ('last_refill', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
