# Generated by Django 5.0.7 on 2024-07-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_refill',
        ),
        migrations.AddField(
            model_name='user',
            name='last_interaction',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='limit',
            field=models.IntegerField(default=100),
        ),
    ]
