# Generated by Django 5.0.7 on 2024-07-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0002_remove_user_last_refill_user_last_interaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='energy',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='limit',
            field=models.IntegerField(default=1000),
        ),
    ]
