# Generated by Django 5.0.7 on 2024-07-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0003_user_energy_alter_user_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tap',
            field=models.IntegerField(default=1),
        ),
    ]
