# Generated by Django 5.0.7 on 2024-07-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0004_user_tap'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coin_add',
            field=models.IntegerField(default=1),
        ),
    ]
