# Generated by Django 5.0.7 on 2024-07-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0005_user_coin_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='coin_add',
        ),
    ]
