# Generated by Django 5.0.7 on 2024-07-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0006_remove_user_coin_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
