# Generated by Django 5.0.7 on 2024-07-21 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0007_user_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sub',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RefFriendModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=255, unique=True)),
                ('ref_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref_friends', to='botapp.user')),
            ],
        ),
    ]
