# Generated by Django 5.0.7 on 2024-07-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0008_alter_user_sub_reffriendmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reffriendmodel',
            name='ref_friend',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
