# Generated by Django 5.0.7 on 2024-07-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0009_alter_reffriendmodel_ref_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reffriendmodel',
            name='ref_friend',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reffriendmodel',
            name='telegram_id',
            field=models.CharField(max_length=255),
        ),
    ]
