# Generated by Django 5.0.7 on 2024-07-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0010_alter_reffriendmodel_ref_friend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
